WifiDog: http.c File Reference
http.c File Reference
HTTP IO functions.
Functions
void http_callback_404 (httpd *webserver, request *r)
Callback for libhttpd, main entry point for captive portal.
void http_callback_wifidog (httpd *webserver, request *r)
Callback for libhttpd.
void http_callback_about (httpd *webserver, request *r)
Callback for libhttpd.
void http_callback_status (httpd *webserver, request *r)
Callback for libhttpd.
void http_send_redirect_to_auth (request *r, char *urlFragment, char *text)
Convenience function to redirect the web browser to the auth server.
void http_send_redirect (request *r, char *url, char *text)
Sends a redirect to the web browser.
void http_callback_auth (httpd *webserver, request *r)
Callback for libhttpd, main entry point post login for auth confirmation.
void send_http_page (request *r, const char *title, const char *message)
Sends a HTML page to web browser.
Variables
pthread_mutex_t client_list_mutex
Detailed Description
HTTP IO functions.
Author:
Copyright (C) 2004 Philippe April <papril777@yahoo.com>
Copyright (C) 2007 Benoit Grégoire
Copyright (C) 2007 David Bird <david@coova.com>
Definition in file http.c.
Function Documentation
void http_callback_404 (httpd * webserver, request * r)
Callback for libhttpd, main entry point for captive portal.
The 404 handler is also responsible for redirecting to the auth server
Definition at line 64 of file http.c.
References _auth_serv_t::authserv_login_script_path_fragment, config_get_config(), debug, get_auth_server(), s_config::gw_address, s_config::gw_id, s_config::gw_port, http_send_redirect_to_auth(), MAX_BUF, and send_http_page().
void http_callback_about (httpd * webserver, request * r)
Callback for libhttpd.
Definition at line 148 of file http.c.
References send_http_page().
void http_callback_auth (httpd * webserver, request * r)
Callback for libhttpd, main entry point post login for auth confirmation.
Definition at line 238 of file http.c.
References auth_server_request(), s_config::auth_servers, authenticate_client(), _auth_serv_t::authserv_msg_script_path_fragment, client_list_append(), client_list_delete(), client_list_find(), config_get_config(), _t_client::counters, debug, _t_client::fw_connection_state, GATEWAY_MESSAGE_ACCOUNT_LOGGED_OUT, get_auth_server(), http_send_redirect_to_auth(), _t_counters::incoming, _t_client::ip, _t_client::mac, _t_counters::outgoing, REQUEST_TYPE_LOGOUT, send_http_page(), and _t_client::token.
void http_callback_status (httpd * webserver, request * r)
Callback for libhttpd.
Definition at line 154 of file http.c.
References config_get_config(), debug, s_config::httpdpassword, s_config::httpdrealm, s_config::httpdusername, and send_http_page().
void http_callback_wifidog (httpd * webserver, request * r)
Callback for libhttpd.
Definition at line 142 of file http.c.
References send_http_page().
void http_send_redirect (request * r, char * url, char * text)
Sends a redirect to the web browser.
Parameters:
r The request
url The url to redirect to
text The text to include in the redirect header and the manual redirect link title. NULL is acceptable
Definition at line 208 of file http.c.
References debug, and send_http_page().
Referenced by http_send_redirect_to_auth().
void http_send_redirect_to_auth (request * r, char * urlFragment, char * text)
Convenience function to redirect the web browser to the auth server.
Convenience function to redirect the web browser to the authe server.
Parameters:
r The request
urlFragment The end of the auth server URL to redirect to (the part after path)
text The text to include in the redirect header ant the mnual redirect title
Definition at line 178 of file http.c.
References _auth_serv_t::authserv_hostname, _auth_serv_t::authserv_http_port, _auth_serv_t::authserv_path, _auth_serv_t::authserv_ssl_port, _auth_serv_t::authserv_use_ssl, get_auth_server(), and http_send_redirect().
Referenced by authenticate_client(), http_callback_404(), and http_callback_auth().
void send_http_page (request * r, const char * title, const char * message)
Sends a HTML page to web browser.
Definition at line 305 of file http.c.
References config_get_config(), debug, s_config::gw_id, s_config::htmlmsgfile, and safe_malloc().
Referenced by authenticate_client(), http_callback_404(), http_callback_about(), http_callback_auth(), http_callback_status(), http_callback_wifidog(), and http_send_redirect().
Variable Documentation
pthread_mutex_t client_list_mutex
Global mutex to protect access to the client list
Definition at line 48 of file client_list.c.