WifiDog: ping_thread.c File Reference
ping_thread.c File Reference
Periodically checks in with the central auth server so the auth server knows the gateway is still up. Note that this is NOT how the gateway detects that the central server is still up.
Functions
static void ping (void)
void thread_ping (void *arg)
Periodically checks on the auth server to see if it's alive.
update (void)
Variables
time_t started_time
Detailed Description
Periodically checks in with the central auth server so the auth server knows the gateway is still up. Note that this is NOT how the gateway detects that the central server is still up.
Author:
Copyright (C) 2004 Alexandre Carmel-Veilleux <acv@miniguru.ca>
Definition in file ping_thread.c.
Function Documentation
static void ping (void) [static]
We don't have to use FD_ISSET() because there was only one fd.
Definition at line 97 of file ping_thread.c.
References _auth_serv_t::authserv_hostname, _auth_serv_t::authserv_path, _auth_serv_t::authserv_ping_script_path_fragment, config_get_config(), connect_auth_server(), debug, get_auth_server(), and MAX_BUF.
Referenced by thread_ping().
void thread_ping (void * arg)
Periodically checks on the auth server to see if it's alive.
Launches a thread that periodically checks in with the wifidog auth server to perform heartbeat function.
Parameters:
arg NULL
Todo:
This thread loops infinitely, need a watchdog to verify that it is still running?
Definition at line 64 of file ping_thread.c.
References s_config::checkinterval, config_get_config(), debug, and ping().