WifiDog: safe.c File Reference
safe.c File Reference
Safe versions of stdlib/string functions that error out and exit if memory allocation fails.
Functions
void * safe_malloc (size_t size)
Safe version of malloc.
char * safe_strdup (const char *s)
int safe_asprintf (char **strp, const char *fmt,...)
int safe_vasprintf (char **strp, const char *fmt, va_list ap)
pid_t safe_fork (void)
Variables
httpd * webserver
Detailed Description
Safe versions of stdlib/string functions that error out and exit if memory allocation fails.
Author:
Copyright (C) 2005 Mina Naguib <mina@ilesansfil.org>
Definition in file safe.c.
Function Documentation
void* safe_malloc (size_t size)
Safe version of malloc.
Definition at line 45 of file safe.c.
References debug.
Referenced by _parse_firewall_rule(), client_list_append(), parse_commandline(), and send_http_page().